//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 01:42:12 AM EEST 
//


package model.dblp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for proceedings element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="proceedings">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{}publication">
 *         &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="mdate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="publtype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "proceedings")
public class Proceedings
    extends Publication
{

    @XmlAttribute(required = true)
    protected String key;
    @XmlAttribute
    protected String mdate;
    @XmlAttribute
    protected String publtype;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the mdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMdate() {
        return mdate;
    }

    /**
     * Sets the value of the mdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMdate(String value) {
        this.mdate = value;
    }

    /**
     * Gets the value of the publtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubltype() {
        return publtype;
    }

    /**
     * Sets the value of the publtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubltype(String value) {
        this.publtype = value;
    }

}
